# Generated by Django 4.2.1 on 2023-05-10 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20230510_0840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='paymant_status',
            new_name='payment_status',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='colletions',
            new_name='collection',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='feature_product',
        ),
        migrations.AddField(
            model_name='collection',
            name='featured_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='store.product'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
